apiVersion: v2
name: no-latest-tag-webhook
description: Kubernetes ValidatingAdmissionWebhook that blocks pods using :latest or untagged container images
type: application
version: 1.0.11
appVersion: "1.0.0"
keywords:
  - webhook
  - admission
  - security
  - image-policy
maintainers:
  - name: omkar-shelke25
    url: https://github.com/omkar-shelke25
sources:
  - https://github.com/omkar-shelke25/admission-webhook-no-latest