apiVersion: v1
kind: Service
metadata:
  name: {{ include "no-latest-tag-webhook.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "no-latest-tag-webhook.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "no-latest-tag-webhook.selectorLabels" . | nindent 4 }}
  ports:
    - name: https
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP